<!--  Copyright (c) 0x5BFA. All rights reserved. Licensed under MIT License.  -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<AssemblyName>WinUIDesigner.DesignerHost</AssemblyName>
		<RootNamespace>WinUIDesigner.DesignerHost</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="Microsoft.VisualStudio.DesignTools.UtilityBase">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.UtilityBase.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.DesignerContractBase">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.DesignerContractBase.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.DesignerContract">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.DesignerContract.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.DesignerHost">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.DesignerHost.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.XamlDesignerHost">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.XamlDesignerHost.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>
