// Copyright (c) 0x5BFA. All rights reserved.
// Licensed under MIT License.

using System.Reflection;
using System.Windows;
using Microsoft.VisualStudio.DesignTools.Utility;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Mono.Cecil;
using WinUIDesigner;
using WinUIDesigner.Toolbox;

[TestClass]
public sealed class ToolboxTests
{
    private static readonly IReadOnlyDictionary<string, string> ExcludedVisualTypes =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Microsoft.UI.Xaml.Controls.Page"] = "Document root; create a XAML document rather than insert a Page.",
            ["Microsoft.UI.Xaml.Controls.SwapChainBackgroundPanel"] = "Legacy DirectX surface restricted to the visual-tree root; use SwapChainPanel.",
            ["Microsoft.UI.Xaml.Controls.BreadcrumbBarItem"] = "Container generated by BreadcrumbBar from its data items.",
            ["Microsoft.UI.Xaml.Controls.CalendarViewDayItem"] = "Day container generated by CalendarView.",
            ["Microsoft.UI.Xaml.Controls.CommandBarOverflowPresenter"] = "CommandBar overflow template presenter.",
            ["Microsoft.UI.Xaml.Controls.FlyoutPresenter"] = "Flyout template presenter.",
            ["Microsoft.UI.Xaml.Controls.GridViewHeaderItem"] = "GridView group-header container.",
            ["Microsoft.UI.Xaml.Controls.GroupItem"] = "Generated group container.",
            ["Microsoft.UI.Xaml.Controls.ListViewHeaderItem"] = "ListView group-header container.",
            ["Microsoft.UI.Xaml.Controls.MediaPlayerPresenter"] = "MediaPlayerElement template presenter.",
            ["Microsoft.UI.Xaml.Controls.MenuFlyoutPresenter"] = "MenuFlyout template presenter.",
            ["Microsoft.UI.Xaml.Controls.RevealListViewItemPresenter"] = "ListView item template presenter.",
            ["Microsoft.UI.Xaml.Controls.ScrollContentPresenter"] = "ScrollViewer template presenter.",
            ["Microsoft.UI.Xaml.Controls.TreeViewList"] = "TreeView implementation list.",
            ["Microsoft.UI.Xaml.Controls.Primitives.CalendarPanel"] = "CalendarView implementation panel.",
            ["Microsoft.UI.Xaml.Controls.Primitives.CarouselPanel"] = "Items-control implementation panel.",
            ["Microsoft.UI.Xaml.Controls.Primitives.ColorPickerSlider"] = "ColorPicker implementation slider.",
            ["Microsoft.UI.Xaml.Controls.Primitives.CommandBarFlyoutCommandBar"] = "CommandBarFlyout implementation command bar.",
            ["Microsoft.UI.Xaml.Controls.Primitives.GridViewItemPresenter"] = "GridView item template presenter.",
            ["Microsoft.UI.Xaml.Controls.Primitives.InfoBarPanel"] = "InfoBar implementation panel.",
            ["Microsoft.UI.Xaml.Controls.Primitives.ListViewItemPresenter"] = "ListView item template presenter.",
            ["Microsoft.UI.Xaml.Controls.Primitives.MonochromaticOverlayPresenter"] = "Template overlay presenter.",
            ["Microsoft.UI.Xaml.Controls.Primitives.NavigationViewItemPresenter"] = "NavigationView item template presenter.",
            ["Microsoft.UI.Xaml.Controls.Primitives.PivotHeaderItem"] = "Pivot generated header.",
            ["Microsoft.UI.Xaml.Controls.Primitives.PivotHeaderPanel"] = "Pivot header implementation panel.",
            ["Microsoft.UI.Xaml.Controls.Primitives.PivotPanel"] = "Pivot implementation panel.",
            ["Microsoft.UI.Xaml.Controls.Primitives.TabViewListView"] = "TabView implementation list.",
        };

    [STATestMethod]
    public void RejectsInvalidRequestsWithoutAllocatingNativeData()
    {
        var provider = new WinUIStaticToolboxItemProvider();
        ushort format = checked((ushort)DataFormats.GetDataFormat(WinUIStandardToolboxItems.ClipboardFormat).Id);

        Assert.IsTrue(provider.GetItemContent(
            "Microsoft.UI.Xaml.Controls.Page, " + WinUIStandardToolboxItems.AssemblyIdentity,
            format,
            out IntPtr invalid) < 0);
        Assert.AreEqual(IntPtr.Zero, invalid);
        Assert.IsTrue(provider.GetItemContent(
            WinUIStandardToolboxItems.GetItemId("Microsoft.UI.Xaml.Controls.Button"),
            1,
            out invalid) < 0);
        Assert.AreEqual(IntPtr.Zero, invalid);
        Assert.IsTrue(provider.GetItemContent(null!, format, out invalid) < 0);
        Assert.AreEqual(IntPtr.Zero, invalid);
        Assert.AreEqual(WinUIStandardToolboxItems.TypeNames.Count,
            WinUIStandardToolboxItems.TypeNames.Distinct().Count(),
            "Toolbox item IDs must be unique.");
    }

    [STATestMethod]
    public void EncodesEveryStandardItemAndPreservesCreationMetadata()
    {
        var provider = new WinUIStaticToolboxItemProvider();
        ushort format = checked((ushort)DataFormats.GetDataFormat(WinUIStandardToolboxItems.ClipboardFormat).Id);

        foreach (string type in WinUIStandardToolboxItems.TypeNames)
        {
            Assert.AreEqual(0,
                provider.GetItemContent(WinUIStandardToolboxItems.GetItemId(type), format, out IntPtr global),
                "Provider must supply " + type);
            IntPtr address = NativeMethods.GlobalLock(global);
            try
            {
                Assert.AreNotEqual(IntPtr.Zero, address, "GlobalLock must succeed for " + type);
                IDictionary<string, object> decoded = ToolEncoder.Decode(address);
                Assert.AreEqual(WinUIStandardToolboxItems.GetItemId(type), decoded["CreationTypeName"]);
                var assembly = (AssemblyName)decoded["CreationAssemblyName"];
                Assert.AreEqual(WinUIStandardToolboxItems.AssemblyIdentity, assembly.FullName);
                Assert.IsTrue(string.IsNullOrEmpty(assembly.CodeBase));
                Assert.AreEqual("WinUI", decoded["CreationTypeSdkAppliesTo"]);
                Assert.AreEqual("Windows, Version=10.0", decoded["TargetPlatform"]);
                Assert.AreEqual("[CreationTool]", decoded["ToolTypeName"]);
            }
            finally
            {
                if (address != IntPtr.Zero) NativeMethods.GlobalUnlock(global);
                NativeMethods.GlobalFree(global);
            }
        }
    }

    [TestMethod]
    public void CatalogAccountsForEveryConstructibleSdkVisualType()
    {
        using AssemblyDefinition projection = AssemblyDefinition.ReadAssembly(GetProjectionPath());
        var candidates = new HashSet<string>(projection.MainModule.Types
            .Where(type => IsVisualCandidate(type, projection))
            .Select(type => type.FullName), StringComparer.Ordinal);
        var catalog = new HashSet<string>(WinUIStandardToolboxItems.TypeNames, StringComparer.Ordinal);

        string[] missing = candidates
            .Where(type => !catalog.Contains(type) && !ExcludedVisualTypes.ContainsKey(type))
            .OrderBy(type => type, StringComparer.Ordinal)
            .ToArray();
        Assert.AreEqual(0, missing.Length,
            "Unclassified SDK visual types (register or explicitly exclude them): " + string.Join(", ", missing));

        foreach (var exclusion in ExcludedVisualTypes)
        {
            Assert.IsTrue(candidates.Contains(exclusion.Key), "Excluded type must exist: " + exclusion.Key);
            Assert.IsFalse(catalog.Contains(exclusion.Key), "Excluded type must not be registered: " + exclusion.Key);
            Assert.IsFalse(string.IsNullOrWhiteSpace(exclusion.Value), "Excluded type needs a reason: " + exclusion.Key);
        }
    }

    [TestMethod]
    public void CatalogItemsArePublicConstructibleVisualElements()
    {
        using AssemblyDefinition projection = AssemblyDefinition.ReadAssembly(GetProjectionPath());

        foreach (string typeName in WinUIStandardToolboxItems.TypeNames)
        {
            TypeDefinition? type = projection.MainModule.GetType(typeName);
            Assert.IsNotNull(type, "Catalog type must exist: " + typeName);
            Assert.IsTrue(type.IsPublic && !type.IsAbstract && !type.HasGenericParameters,
                "Catalog item must be a public concrete type: " + typeName);
            Assert.IsTrue(type.Methods.Any(method => method.IsConstructor && method.IsPublic && !method.IsStatic && !method.HasParameters),
                "Catalog item must have a public default constructor: " + typeName);
            Assert.IsTrue(DerivesFromFrameworkElement(type, projection),
                "Catalog item must derive from FrameworkElement: " + typeName);
        }
    }

    private static string GetProjectionPath()
    {
        string? configuredPath = Environment.GetEnvironmentVariable("WINUIDESIGNER_PROJECTION_PATH");
        if (!string.IsNullOrWhiteSpace(configuredPath)) return configuredPath;

        for (DirectoryInfo? directory = new(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
        {
            if (File.Exists(Path.Combine(directory.FullName, "WinUIDesigner.slnx")))
            {
                return Path.Combine(directory.FullName,
                    "src", "WinUIDesigner.Surface", "bin", "Release",
                    "net10.0-windows10.0.26100.0", "Microsoft.WinUI.dll");
            }
        }

        throw new FileNotFoundException(
            "Could not locate WinUIDesigner.slnx from the test output directory. Set WINUIDESIGNER_PROJECTION_PATH to Microsoft.WinUI.dll.");
    }

    private static bool IsVisualCandidate(TypeDefinition type, AssemblyDefinition projection)
    {
        if (!type.IsPublic || type.IsAbstract || type.HasGenericParameters ||
            !type.Methods.Any(method => method.IsConstructor && method.IsPublic && !method.IsStatic && !method.HasParameters))
        {
            return false;
        }

        return DerivesFromFrameworkElement(type, projection);
    }

    private static bool DerivesFromFrameworkElement(TypeDefinition type, AssemblyDefinition projection)
    {
        var visited = new HashSet<string>();
        for (TypeDefinition? current = type; current is not null && visited.Add(current.FullName);)
        {
            if (current.FullName == "Microsoft.UI.Xaml.FrameworkElement") return true;
            current = current.BaseType is null ? null : projection.MainModule.GetType(current.BaseType.FullName);
        }

        return false;
    }
}
