<!--  Copyright (c) 0x5BFA. All rights reserved. Licensed under MIT License.  -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<AssemblyName>WinUIDesigner</AssemblyName>
		<RootNamespace>WinUIDesigner</RootNamespace>
		<GeneratePkgDefFile>true</GeneratePkgDefFile>
		<VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
		<VsixDeployOnDebug>true</VsixDeployOnDebug>
		<StartAction>Program</StartAction>
		<StartProgram>$(VsInstallRoot)\Common7\IDE\devenv.exe</StartProgram>
		<StartArguments>/rootsuffix Exp</StartArguments>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.9.820" PrivateAssets="all" />
		<PackageReference Include="MonoMod.RuntimeDetour" Version="25.3.4" />
		<PackageReference Include="System.ValueTuple" Version="4.6.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectCapability Include="CreateVsixContainer" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Microsoft.VisualStudio.Shell">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Shell.15.0.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.Threading">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Threading.17.x\Microsoft.VisualStudio.Threading.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.UwpSurfaceDesigner">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.UwpSurfaceDesigner.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.Extensibility">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.DesignTools.Extensibility.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.Shell.Interop">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Shell.Interop.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.Shell.Framework">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Shell.Framework.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.Interop">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Interop.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.UtilityBase">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.UtilityBase.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.RuntimeHostBase">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.RuntimeHostBase.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.RuntimeHost">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.RuntimeHost.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.Markup">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.Markup.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.DesignerHost">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.DesignerHost.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.SurfaceDesigner">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.SurfaceDesigner.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.DesignerContract">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.DesignerContract.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.DesignerContractBase">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.DesignerContractBase.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.Utility">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.Utility.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.XamlLanguageServiceBase">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.XamlLanguageServiceBase.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.VisualStudio.DesignTools.XamlDesignerHost">
			<HintPath>$(VsInstallRoot)\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.DesignTools.XamlDesignerHost.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="PresentationCore" />
		<Reference Include="PresentationFramework" />
		<Reference Include="WindowsBase" />
		<Reference Include="System.Drawing" />
	</ItemGroup>

	<ItemGroup>
		<None Include="source.extension.vsixmanifest" />
		<VSIXSourceItem Include="..\..\LICENSE">
			<TargetPath>LICENSE.txt</TargetPath>
		</VSIXSourceItem>
		<EmbeddedResource Update="Resources\VSPackage.resx">
			<LogicalName>VSPackage.resources</LogicalName>
		</EmbeddedResource>
		<VSIXSourceItem Include="Resources\logo-90.png">
			<TargetPath>WinUIDesignerIcon.png</TargetPath>
		</VSIXSourceItem>
		<VSIXSourceItem Include="Resources\preview.png">
			<TargetPath>WinUIDesignerPreview.png</TargetPath>
		</VSIXSourceItem>
		<VSIXSourceItem Include="..\WinUIDesigner.Surface\bin\$(Configuration)\$(WinUIDesignerSurfaceTargetFramework)\win-x64\publish\WinUISurface.exe">
			<TargetPath>WinUISurface.exe</TargetPath>
		</VSIXSourceItem>
	</ItemGroup>

	<Target Name="PublishWinUIDesignerSurface"
	        BeforeTargets="GetVsixSourceItems"
	        Condition="'$(CreateVsixContainer)' != 'false' and '$(DesignTimeBuild)' != 'true'">
		<MSBuild Projects="$(MSBuildProjectDirectory)\..\WinUIDesigner.Surface\WinUIDesigner.Surface.csproj"
		         Targets="Publish"
		         Properties="RuntimeIdentifier=win-x64"
		         BuildInParallel="false" />
	</Target>

</Project>
