# Copyright (c) 0x5BFA. All rights reserved.
# Licensed under the MIT license.

# Update the PAT every year from https://dev.azure.com/0x5bfa/_usersSettings/tokens

name: CD

on:
  workflow_dispatch:

run-name: 'Publish VSIX to Visual Studio Marketplace'

permissions:
  contents: read

jobs:
  package:
    runs-on: windows-2025-vs2026
    timeout-minutes: 30

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
      - name: Set up .NET 10 SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Build solution
        shell: pwsh
        run: |
          msbuild .\WinUIDesigner.slnx /restore /p:Configuration=Release /p:DeployExtension=false /nologo /verbosity:minimal /m

      - name: Publish to Visual Studio Marketplace
        shell: pwsh
        working-directory: ${{ github.workspace }}\src\WinUIDesigner.Vsix
        env:
          VS_MARKETPLACE_PAT: ${{ secrets.VS_MARKETPLACE_PAT }}
        run: |
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $vsInstallRoot = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
          $publisher = Join-Path $vsInstallRoot 'VSSDK\VisualStudioIntegration\Tools\Bin\VsixPublisher.exe'

          & $publisher publish `
            -payload '.\bin\Release\net472\WinUIDesigner.vsix' `
            -publishManifest '.\publishManifest.json' `
            -personalAccessToken $env:VS_MARKETPLACE_PAT
